### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by MichalBryxi** [igorpreston/ember-cli-mapbox-map#1]
Hi, just found your library. Wanted to give it a try, but after `ember install ember-cli-mapbox-map`, setting the API key and including `{{mapbox-map ...` into my template I get following error:

```
Uncaught Error: Could not find module `ember-cli-mapbox/initializers/mapbox` imported from `malajsie/initializers/mapbox`requireFrom @ loader.js:110reify @ loader.js:97mod.state @ loader.js:140tryFinally @ loader.js:21requireModule @ loader.js:139(anonymous function) @ ember-load-initializers.js:23default @ ember-load-initializers.js:20(anonymous function) @ app.js:15mod.state @ loader.js:141tryFinally @ loader.js:21requireModule @ loader.js:139(anonymous function) @ app-boot.js:25
```

Strange is that the module is installed in `node_modules/ember-cli-mapbox-map`. I would think that since it's trying to explore the path `ember-cli-mapbox/initializers/mapbox`, it would be directory without *-map* at the end.

Thanks for any hint in advance!

**Comment by igorpreston** [comment]
@MichalBryxi hey thank you for checking out and posting the issue. It was caused by wrong path used to import initializers from the addon. I called the addon _ember-cli-mapbox_ at first, but this name was already taken on npm, so I changed it, but forgot changing the paths.

Anyway, fixed the issue and already pushed update both to github and npm.
You can install updated version with 
```
ember install ember-cli-mapbox-map
```

Feel free to ask for support if you have any further questions while using the addon.

**Comment by MichalBryxi** [comment]
Thanks for that prompt reaction, but I cannot confirm that the bug is fixed: https://gist.github.com/MichalBryxi/3723d88fb271da68676a

Still seeing:

```
Uncaught Error: Could not find module `ember-cli-mapbox/components/mapbox-map` imported from `malajsie/components/mapbox-map`
```

**Comment by igorpreston** [comment]
@MichalBryxi ok, fixed the issue finally. Last updated version is: 0.1.5.
These bugs also occured in both component and service. I installed the addon in new ember app and it worked.

**Comment by MichalBryxi** [comment]
Woot! 

![url](https://cloud.githubusercontent.com/assets/847473/9096017/ed0d6676-3bba-11e5-8a57-ac288677f761.jpg)
